### PR TITLE
Fix can't build kernel

### PR DESCRIPTION
**Pull request by Coconutat**
I used Ubuntu 20.04 and Proton-cLang to compile the kernel myself, and it was successfully compiled.  
I added these:
1. KernelSU Sync Scripts：use all to sync all code. use stand to update code.If stand version go wrong,use all.
2. Build Script Remake Version:Just a build kernel script.
3. Fix some ksu symbol in fs and drivers
4. Github Action .yml: I hope it can auto build kernel by Github Action.(Still in test)
5.  If you want see my compiled kernel image,in here:[Releases](https://github.com/Coconutat/android_kernel_SM-A107F/releases)

### CODE REVIEW

**Comment by Coconutat** [comment]
Github Action can build kernel now.It's passed test.Here is:[Github Action](https://github.com/Coconutat/android_kernel_SM-A107F/actions/runs/5331175057)

**Comment by anuragpindoriya** [comment]
> Github Action can build kernel now.It's passed test.Here is:[Github Action](https://github.com/Coconutat/android_kernel_SM-A107F/actions/runs/5331175057)

ok that's great 
Any by the way thank you very very much and also sorry for this trouble

**Comment by Coconutat** [comment]
> > Github Action can build kernel now.It's passed test.Here is:[Github Action](https://github.com/Coconutat/android_kernel_SM-A107F/actions/runs/5331175057)
> 
> ok that's great Any by the way thank you very very much and also sorry for this trouble

If possible, please visit this website and publish a TWRP package that can be flashed.
https://forum.xda-developers.com/t/kernel-kernelsu-for-samsung-galaxy-a10s-sm-a107f.4598373/

**Comment by anuragpindoriya** [comment]
> > > Github Action can build kernel now.It's passed test.Here is:[Github Action](https://github.com/Coconutat/android_kernel_SM-A107F/actions/runs/5331175057)
> > 
> > 
> > ok that's great Any by the way thank you very very much and also sorry for this trouble
> 
> If possible, please visit this website and publish a TWRP package that can be flashed. https://forum.xda-developers.com/t/kernel-kernelsu-for-samsung-galaxy-a10s-sm-a107f.4598373/

but can you tell how i use image.gz file to flash in twrp 
I'm not know about this.
Can you help me to make  TWRP package that can be flashed and it process.

**Comment by Coconutat** [comment]
> > > > Github Action can build kernel now.It's passed test.Here is:[Github Action](https://github.com/Coconutat/android_kernel_SM-A107F/actions/runs/5331175057)
> > > 
> > > 
> > > ok that's great Any by the way thank you very very much and also sorry for this trouble
> > 
> > 
> > If possible, please visit this website and publish a TWRP package that can be flashed. https://forum.xda-developers.com/t/kernel-kernelsu-for-samsung-galaxy-a10s-sm-a107f.4598373/
> 
> but can you tell how i use image.gz file to flash in twrp I'm not know about this. Can you help me to make TWRP package that can be flashed and it process.

You need AnyKernel3.In here:https://github.com/osm0sis/AnyKernel3

Then read the AnyKernel3 Readme.
And you need test it by yourself.
BECAUSE I DON'T HAVE SAMSUNG A10S.
Remember backup your boot,vendor, system etc...
Or you have your device firmware.

**Comment by anuragpindoriya** [comment]
> You need AnyKernel3.In here:https://github.com/osm0sis/AnyKernel3
> 
> Then read the AnyKernel3 Readme. And you need test it by yourself. BECAUSE I DON'T HAVE SAMSUNG A10S. Remember backup your boot,vendor, system etc... Or you have your device firmware.

we need A "image.dz-dts" file but it is not create during compilation  here is log 

WARNING: drivers/power/supply/mt6359_battery: 'charger_notifier' exported twice. Previous export was in vmlinux
WARNING: drivers/power/supply/mt6359_battery: 'register_mtk_battery_notifier' exported twice. Previous export was in vmlinux
WARNING: drivers/power/supply/mt6359_battery: 'unre_mtk_battery_notifier' exported twice. Previous export was in vmlinux
  GZIP    arch/arm64/boot/Image.gz
WARNING: drivers/power/supply/mt6359_battery: 'wt_set_batt_cycle_fv' exported twice. Previous export was in vmlinux
WARNING: sound/soc/codecs/mt6359-accdet: 'accdet_read_audio_res' exported twice. Previous export was in vmlinux
WARNING: sound/soc/codecs/mt6359-accdet: 'accdet_late_init' exported twice. Previous export was in vmlinux
  CC      drivers/mmc/host/sdhci-pltfm.mod.o
  CC      drivers/mmc/host/sdhci.mod.o
  CC      drivers/power/supply/mt6359_battery.mod.o
  CC      drivers/tty/serial/8250/8250_of.mod.o
  CC      drivers/usb/gadget/udc/dummy_hcd.mod.o
  CC      kernel/kheaders.mod.o
  CC      kernel/trace/trace_mmstat.mod.o
  CC      net/ipv4/tcp_htcp.mod.o
  CC      net/ipv4/tcp_westwood.mod.o
  CC      sound/soc/codecs/mt6359-accdet.mod.o
  LD [M]  drivers/mmc/host/sdhci-pltfm.ko
  LD [M]  drivers/mmc/host/sdhci.ko
  LD [M]  drivers/power/supply/mt6359_battery.ko
  LD [M]  drivers/tty/serial/8250/8250_of.ko
  LD [M]  drivers/usb/gadget/udc/dummy_hcd.ko
  LD [M]  kernel/kheaders.ko
  LD [M]  kernel/trace/trace_mmstat.ko
  LD [M]  net/ipv4/tcp_htcp.ko
  LD [M]  net/ipv4/tcp_westwood.ko
  LD [M]  sound/soc/codecs/mt6359-accdet.ko
make[1]: Leaving directory '/home/runner/work/android_kernel_SM-A107F/android_kernel_SM-A107F/out'

To make TWRP package we need this file

**Comment by anuragpindoriya** [comment]
And can you also check this https://github.com/anuragpindoriya/android_kernel_smasung_m515f/actions/runs/5362572818/jobs/9729549216

**Comment by Coconutat** [comment]
> > You need AnyKernel3.In here:https://github.com/osm0sis/AnyKernel3
> > Then read the AnyKernel3 Readme. And you need test it by yourself. BECAUSE I DON'T HAVE SAMSUNG A10S. Remember backup your boot,vendor, system etc... Or you have your device firmware.
> 
> we need A "image.dz-dts" file but it is not create during compilation here is log
> 
> WARNING: drivers/power/supply/mt6359_battery: 'charger_notifier' exported twice. Previous export was in vmlinux WARNING: drivers/power/supply/mt6359_battery: 'register_mtk_battery_notifier' exported twice. Previous export was in vmlinux WARNING: drivers/power/supply/mt6359_battery: 'unre_mtk_battery_notifier' exported twice. Previous export was in vmlinux GZIP arch/arm64/boot/Image.gz WARNING: drivers/power/supply/mt6359_battery: 'wt_set_batt_cycle_fv' exported twice. Previous export was in vmlinux WARNING: sound/soc/codecs/mt6359-accdet: 'accdet_read_audio_res' exported twice. Previous export was in vmlinux WARNING: sound/soc/codecs/mt6359-accdet: 'accdet_late_init' exported twice. Previous export was in vmlinux CC drivers/mmc/host/sdhci-pltfm.mod.o CC drivers/mmc/host/sdhci.mod.o CC drivers/power/supply/mt6359_battery.mod.o CC drivers/tty/serial/8250/8250_of.mod.o CC drivers/usb/gadget/udc/dummy_hcd.mod.o CC kernel/kheaders.mod.o CC kernel/trace/trace_mmstat.mod.o CC net/ipv4/tcp_htcp.mod.o CC net/ipv4/tcp_westwood.mod.o CC sound/soc/codecs/mt6359-accdet.mod.o LD [M] drivers/mmc/host/sdhci-pltfm.ko LD [M] drivers/mmc/host/sdhci.ko LD [M] drivers/power/supply/mt6359_battery.ko LD [M] drivers/tty/serial/8250/8250_of.ko LD [M] drivers/usb/gadget/udc/dummy_hcd.ko LD [M] kernel/kheaders.ko LD [M] kernel/trace/trace_mmstat.ko LD [M] net/ipv4/tcp_htcp.ko LD [M] net/ipv4/tcp_westwood.ko LD [M] sound/soc/codecs/mt6359-accdet.ko make[1]: Leaving directory '/home/runner/work/android_kernel_SM-A107F/android_kernel_SM-A107F/out'
> 
> To make TWRP package we need this file

Maybe don't need,Not All Kernel name is Image.gz-dtb/.dts.Because not all kernel need DTS/DTC.Maybe you need unpack your boot.img to check it.

**Comment by Coconutat** [comment]
> 你能不能也检查一下这个[https：//github.com/anuragpindoriya/android_kernel_smasung_m515f/actions/runs/5362572818/jobs/9729549216](https://github.com/anuragpindoriya/android_kernel_smasung_m515f/actions/runs/5362572818/jobs/9729549216)

Looks like Proton-clang version is too high for this kernel.You need find other Clang.

**Comment by anuragpindoriya** [comment]
> > 你能不能也检查一下这个[https：//github.com/anuragpindoriya/android_kernel_smasung_m515f/actions/runs/5362572818/jobs/9729549216](https://github.com/anuragpindoriya/android_kernel_smasung_m515f/actions/runs/5362572818/jobs/9729549216)
> 
> Looks like Proton-clang version is too high for this kernel.You need find other Clang.

in official Build script 

#!/bin/bash

export ARCH=arm64
mkdir out

BUILD_CROSS_COMPILE=$(pwd)/toolchain/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin/aarch64-linux-android-
KERNEL_LLVM_BIN=$(pwd)/toolchain/llvm-arm-toolchain-ship/10.0/bin/clang
CLANG_TRIPLE=aarch64-linux-gnu-
KERNEL_MAKE_ENV="DTC_EXT=$(pwd)/tools/dtc CONFIG_BUILD_ARM64_DT_OVERLAY=y"

make -j8 -C $(pwd) O=$(pwd)/out $KERNEL_MAKE_ENV ARCH=arm64 CROSS_COMPILE=$BUILD_CROSS_COMPILE REAL_CC=$KERNEL_LLVM_BIN CLANG_TRIPLE=$CLANG_TRIPLE m51_eur_open_defconfig
make -j8 -C $(pwd) O=$(pwd)/out $KERNEL_MAKE_ENV ARCH=arm64 CROSS_COMPILE=$BUILD_CROSS_COMPILE REAL_CC=$KERNEL_LLVM_BIN CLANG_TRIPLE=$CLANG_TRIPLE
 
cp out/arch/arm64/boot/Image $(pwd)/arch/arm64/boot/Image 

can you give me a idea which clang i use and provide a source to download and configure it

**Comment by Coconutat** [comment]
> > > 你能不能也检查一下这个[https：//github.com/anuragpindoriya/android_kernel_smasung_m515f/actions/runs/5362572818/jobs/9729549216](https://github.com/anuragpindoriya/android_kernel_smasung_m515f/actions/runs/5362572818/jobs/9729549216)
> > 
> > 
> > Looks like Proton-clang version is too high for this kernel.You need find other Clang.
> 
> in official Build script
> 
> #!/bin/bash
> 
> export ARCH=arm64 mkdir out
> 
> BUILD_CROSS_COMPILE=$(pwd)/toolchain/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin/aarch64-linux-android- KERNEL_LLVM_BIN=$(pwd)/toolchain/llvm-arm-toolchain-ship/10.0/bin/clang CLANG_TRIPLE=aarch64-linux-gnu- KERNEL_MAKE_ENV="DTC_EXT=$(pwd)/tools/dtc CONFIG_BUILD_ARM64_DT_OVERLAY=y"
> 
> make -j8 -C (pwd)O=(pwd)/out $KERNEL_MAKE_ENV ARCH=arm64 CROSS_COMPILE=$BUILD_CROSS_COMPILE REAL_CC=$KERNEL_LLVM_BIN CLANG_TRIPLE=$CLANG_TRIPLE m51_eur_open_defconfig make -j8 -C (pwd)O=(pwd)/out $KERNEL_MAKE_ENV ARCH=arm64 CROSS_COMPILE=$BUILD_CROSS_COMPILE REAL_CC=$KERNEL_LLVM_BIN CLANG_TRIPLE=$CLANG_TRIPLE
> 
> cp out/arch/arm64/boot/Image $(pwd)/arch/arm64/boot/Image
> 
> can you give me a idea which clang i use and provide a source to download and configure it

It said:toolchain/llvm-arm-toolchain/10.0/bin/clang,which mean,you need Clang based version is 10.0.

**Comment by anuragpindoriya** [comment]
https://github.com/anuragpindoriya/android_kernel_smasung_m515f

This is a github repo can you help me to do this 

> > > > 你能不能也检查一下这个[https：//github.com/anuragpindoriya/android_kernel_smasung_m515f/actions/runs/5362572818/jobs/9729549216](https://github.com/anuragpindoriya/android_kernel_smasung_m515f/actions/runs/5362572818/jobs/9729549216)
> > > 
> > > 
> > > Looks like Proton-clang version is too high for this kernel.You need find other Clang.
> > 
> > 
> > in official Build script
> > #!/bin/bash
> > export ARCH=arm64 mkdir out
> > BUILD_CROSS_COMPILE=$(pwd)/toolchain/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin/aarch64-linux-android- KERNEL_LLVM_BIN=$(pwd)/toolchain/llvm-arm-toolchain-ship/10.0/bin/clang CLANG_TRIPLE=aarch64-linux-gnu- KERNEL_MAKE_ENV="DTC_EXT=$(pwd)/tools/dtc CONFIG_BUILD_ARM64_DT_OVERLAY=y"
> > make -j8 -C (pwd)O=(pwd)/out $KERNEL_MAKE_ENV ARCH=arm64 CROSS_COMPILE=$BUILD_CROSS_COMPILE REAL_CC=$KERNEL_LLVM_BIN CLANG_TRIPLE=$CLANG_TRIPLE m51_eur_open_defconfig make -j8 -C (pwd)O=(pwd)/out $KERNEL_MAKE_ENV ARCH=arm64 CROSS_COMPILE=$BUILD_CROSS_COMPILE REAL_CC=$KERNEL_LLVM_BIN CLANG_TRIPLE=$CLANG_TRIPLE
> > cp out/arch/arm64/boot/Image $(pwd)/arch/arm64/boot/Image
> > can you give me a idea which clang i use and provide a source to download and configure it
> 
> It said:toolchain/llvm-arm-toolchain/10.0/bin/clang,which mean,you need Clang based version is 10.0.

This is my github repo canyou help to compile it . I try but can't make it.

https://github.com/anuragpindoriya/android_kernel_smasung_m515f

**Comment by Coconutat** [comment]
> https://github.com/anuragpindoriya/android_kernel_smasung_m515f
> 
> This is a github repo can you help me to do this
> 
> > > > > 你能不能也检查一下这个[https：//github.com/anuragpindoriya/android_kernel_smasung_m515f/actions/runs/5362572818/jobs/9729549216](https://github.com/anuragpindoriya/android_kernel_smasung_m515f/actions/runs/5362572818/jobs/9729549216)
> > > > 
> > > > 
> > > > Looks like Proton-clang version is too high for this kernel.You need find other Clang.
> > > 
> > > 
> > > in official Build script
> > > #!/bin/bash
> > > export ARCH=arm64 mkdir out
> > > BUILD_CROSS_COMPILE=$(pwd)/toolchain/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin/aarch64-linux-android- KERNEL_LLVM_BIN=$(pwd)/toolchain/llvm-arm-toolchain-ship/10.0/bin/clang CLANG_TRIPLE=aarch64-linux-gnu- KERNEL_MAKE_ENV="DTC_EXT=$(pwd)/tools/dtc CONFIG_BUILD_ARM64_DT_OVERLAY=y"
> > > make -j8 -C (pwd)O=(pwd)/out $KERNEL_MAKE_ENV ARCH=arm64 CROSS_COMPILE=$BUILD_CROSS_COMPILE REAL_CC=$KERNEL_LLVM_BIN CLANG_TRIPLE=$CLANG_TRIPLE m51_eur_open_defconfig make -j8 -C (pwd)O=(pwd)/out $KERNEL_MAKE_ENV ARCH=arm64 CROSS_COMPILE=$BUILD_CROSS_COMPILE REAL_CC=$KERNEL_LLVM_BIN CLANG_TRIPLE=$CLANG_TRIPLE
> > > cp out/arch/arm64/boot/Image $(pwd)/arch/arm64/boot/Image
> > > can you give me a idea which clang i use and provide a source to download and configure it
> > 
> > 
> > It said:toolchain/llvm-arm-toolchain/10.0/bin/clang,which mean,you need Clang based version is 10.0.
> 
> This is my github repo canyou help to compile it . I try but can't make it.
> 
> https://github.com/anuragpindoriya/android_kernel_smasung_m515f

Perhaps when I have time, I will try my best if I have time

**Comment by anuragpindoriya** [comment]
> Perhaps when I have time, I will try my best if I have time

Ya ya sure and thanks for help

**Comment by Coconutat** [comment]
> > Perhaps when I have time, I will try my best if I have time
> 
> Ya ya sure and thanks for help

By the way,What about this A10S kernel? KernelSU doesn't work?

**Comment by Coconutat** [comment]
> > Perhaps when I have time, I will try my best if I have time
> 
> Ya ya sure and thanks for help

This kernel compile issuses are too much.Fix one then this kernel will bring another one.I strongly recommend finding a kernel source code that someone else has maintained and can compile directly.

**Comment by anuragpindoriya** [comment]
> This kernel compile issuses are too much.Fix one then this kernel will bring another one.I strongly recommend finding a kernel source code that someone else has maintained and can compile directly.

Same here 😅

https://opensource.samsung.com/uploadSearch?searchValue=M51

And version is ( M515FXXS4DWA3 )

If by mistake i miss some file 
 
Can you download and try build from samsung official  site

**Comment by Coconutat** [comment]
> > This kernel compile issuses are too much.Fix one then this kernel will bring another one.I strongly recommend finding a kernel source code that someone else has maintained and can compile directly.
> 
> Same here 😅
> 
> https://opensource.samsung.com/uploadSearch?searchValue=M51
> 
> And version is ( M515FXXS4DWA3 )
> 
> If by mistake i miss some file
> 
> Can you download and try build from samsung official site

Still same problem.I think I can't handle it.

**Comment by anuragpindoriya** [comment]
> Still same problem.I think I can't handle it.

Ok no problem 
Can you look in to this if you have time 

https://github.com/anuragpindoriya/android_kernel_samsung_sm6150/actions/runs/5388906544/jobs/9782161017

Repo link https://github.com/anuragpindoriya/android_kernel_samsung_sm6150

**Comment by Coconutat** [comment]
> > Still same problem.I think I can't handle it.
> 
> Ok no problem Can you look in to this if you have time
> 
> https://github.com/anuragpindoriya/android_kernel_samsung_sm6150/actions/runs/5388906544/jobs/9782161017
> 
> Repo link https://github.com/anuragpindoriya/android_kernel_samsung_sm6150

Check this , KSU update a feature.Very unfriendly for old devices!!!
https://github.com/xxmustafacooTR/exynos-linux-stable/commit/8fb7407a9cae2f049001fe3255d4c6c12b97b4c3

**Comment by anuragpindoriya** [comment]
> Check this , KSU update a feature.Very unfriendly for old devices!!! [xxmustafacooTR/exynos-linux-stable@8fb7407](https://github.com/xxmustafacooTR/exynos-linux-stable/commit/8fb7407a9cae2f049001fe3255d4c6c12b97b4c3)

Sorry but i can't understand can help me to do this

**Comment by Coconutat** [comment]
> > Check this , KSU update a feature.Very unfriendly for old devices!!! [xxmustafacooTR/exynos-linux-stable@8fb7407](https://github.com/xxmustafacooTR/exynos-linux-stable/commit/8fb7407a9cae2f049001fe3255d4c6c12b97b4c3)
> 
> Sorry but i can't understand can help me to do this

Right doesn't need it anymore.Forget what I talk about.Official Fixed this problem.

**Comment by anuragpindoriya** [comment]
> Right doesn't need it anymore.Forget what I talk about.Official Fixed this problem.

So, how i fix this can you tell me

**Comment by Coconutat** [comment]
> > Right doesn't need it anymore.Forget what I talk about.Official Fixed this problem.
> 
> So, how i fix this can you tell me

Just re-bulid kernel.You don’t need change anything.

**Comment by anuragpindoriya** [comment]
> Just re-bulid kernel.You don’t need change anything.

Thanks a lot 🙏

**Comment by anuragpindoriya** [comment]
please can you look into this @Coconutat 
https://github.com/anuragpindoriya/android_kernel_SM-A107F/issues/2

**Comment by anuragpindoriya** [comment]
> Just re-bulid kernel.You don’t need change anything.

Hii, long time no see @Coconutat 
Need help can we add kernel su in ( kernel version 3.18.138 ) ?
if yes can you help to implement and compile this kernel 
repo:- https://github.com/anuragpindoriya/on7xelte

**Pull request merged**
